theme: jekyll-theme-cayman
title: Physics & Equality Constrained Artificial Constrained Artificial Neural Networks
description: A physics-informed, noise-aware and equality constrained artificial neural network framework for the solution of forward/inverse problems with multi-fidelity data
