theme: jekyll-theme-cayman
title: Physics $$\And$$ Equality Constrained Artificial Constrained Artificial Neural Networks
description: A physics-informed, noise-aware and equality constrained framework for the solution of forward/inverse problems with multi-fidelity data
